### ISSUE TITLE
Seeing `invalid function selector` error when writing to StateDB.

### ISSUE THREAD

**Issue by cgcardona** [ava-labs/precompile-evm#14]
I've been seeing an `invalid function selector` error when porting over the VRF precompile to precompile-evm and I wanted to confirm it wasn't a bug which I was introducing so I confirmed that it also appears in the HelloWorld precompile. It happens whenever we write to storage. So for example calling the `setGreeting` function in HelloWorld

```zsh
[node1] INFO [07-10|13:41:03.551] <5sHuoVPHJANLGtFMGCWBcdagZPP8ym2WybMewRPnMsr36qgsF Chain> github.com/ava-labs/subnet-evm/rpc/handler.go:403: Served eth_call reqid=80 execTime="683.625µs" procTime="684.232µs" totalTime="684.534µs" err="invalid function selector 0x01ffc9a7"
```

It doesn't appear to affect the precompile working but I wanted to bring it to your attention.

**Comment by ceyonur** [comment]
setGreeting's selector should be `0xa4136862`. This err only returns when the requested function cannot be found in registered ones. I don't think this is related with writing to storage.

**Comment by ceyonur** [comment]
Closing this, feel free to reopen @cgcardona
