### ISSUE TITLE
Add Foundry to Precomile-EVM Devcontainer

### ISSUE THREAD

**Issue by martineckardt** [ava-labs/precompile-evm#69]
Instead of using Remix in the exercises, let's migrate to foundry and Avalanche CLI to the [Precompile-EVM Dev Container](https://github.com/ava-labs/precompile-evm/tree/main/.devcontainer), so have a consistent use of tools across all courses

- [x] Add Foundry to Dockerfile, similar to [Avalanch Starter Kit](https://github.com/ava-labs/avalanche-starter-kit/blob/main/.devcontainer/Dockerfile)
- [x] Add EWOQ Private Key, Foundry to $PATH similar to [Avalanche Starter Kit](https://github.com/ava-labs/avalanche-starter-kit/blob/main/.devcontainer/devcontainer.json)
- [x] Replace instructions from using ANR to Avalanche CLI

**Comment by ashucoder9** [comment]
https://github.com/ava-labs/precompile-evm/issues/69
