### ISSUE TITLE
Remove ANR from Precompile-EVM DevContainer

### ISSUE THREAD

**Issue by martineckardt** [ava-labs/precompile-evm#72]
We now have ANR and Avalanche CLI both in the Dev Container. As soon as we updated the Precompile-EVM course to use Avalanche CLI, we should remove ANR to make the container build faster

```
RUN curl -sSfL https://raw.githubusercontent.com/ava-labs/avalanche-network-runner/main/scripts/install.sh | sh -s
```

Also let's make sure that ANR is nowhere used in the academy course anymore and everything is using Avalanche CLI

**Comment by owenwahlgren** [comment]
ANR mentioned here:
https://academy.avax.network/course/customizing-evm/04-your-evm-blockchain/02-create-your-blockchain
